### ISSUE TITLE
Add linting job to GitHub Actions

### ISSUE THREAD

**Issue by var-bin** [Varbintech/next.varbintechcom#12]
### Config Example
```yaml
name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
```
